### ISSUE TITLE
External API variable naming

### ISSUE THREAD

**Issue by Teebor-Choka** [SK-CERT/ansible-role-kiobi#2]
https://github.com/tomas321/ansible-role-kiobi/blob/1df0fd08320a78b6ad0a53c0c8ee5a22931f1ab1/tasks/main.yml#L6

Consider dropping the `kibana_` prefix from the external API variables' names.

**Comment by Teebor-Choka** [comment]
https://github.com/tomas321/ansible-role-kiobi/blob/1df0fd08320a78b6ad0a53c0c8ee5a22931f1ab1/defaults/main.yml#L8

Please, consider renaming the `target` to `destination` in line with typical ansible module name convention. (`src` and `dest`, not `src` and `target`).

**Comment by tomas321** [comment]
Thank you for the advice.
